block.settings.islandora_altmetric_islandora_altmetric:
  type: block_settings
  label: 'Islandora Altmetric block'
  mapping:
    example:
      type: string
      label: Example

# Schema for the configuration files of the Islandora Altmetric module.
islandora_altmetric.settings:
  type: config_object
  label: 'Islandora Altmetric settings'
  mapping:
    example:
      type: string
      label: 'Example'
